# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

jobs:
  include:
    - os: osx
    - os: linux
      env: PYTHON=python
    - os: linux
      env: PYTHON=python3

matrix:
  julia:
    - 1.0
    - nightly
  allow_failures:
    - julia: nightly
  fast_finish: true
  
notifications:
  email: false
