# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

jobs:
  include:
    - os: osx
    - os: linux
      addons:
        apt:
          packages: python-matplotlib
      env:
        matrix: PYTHON=python
    - os: linux
      addons:
        apt:
          packages: python3-matplotlib
      env:
        matrix: PYTHON=python3 # python 3.5
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
